workflows:
  ios-and-android:
    name: Build iOS and Android
    environment:
      node: 18.17.1
      groups:
        - ios_credentials
    scripts:
      - name: Clean & install dependencies
        script: |
          rm -rf node_modules package-lock.json
          npm install --legacy-peer-deps
          npm install eas-cli --save-dev
      - name: Build iOS IPA
        script: |
          npx eas build --platform ios --non-interactive --profile production
      - name: Build Android AAB
        script: |
          npx eas build --platform android --non-interactive --profile production
    artifacts:
      - build/**/*

