workflows:
  ios-and-android:
    name: Build iOS and Android
    environment:
      node: latest
      npm: latest
      groups:
        - ios_credentials   # optional group for organizing your environment variables
    scripts:
      - name: Install dependencies
        script: |
          npm install --legacy-peer-deps
          npm install -g eas-cli
      - name: Build iOS IPA
        script: |
          eas build --platform ios --non-interactive --profile production
      - name: Build Android AAB
        script: |
          eas build --platform android --non-interactive --profile production
    artifacts:
      - build/**/*
